plugins {
    id 'org.jetbrains.kotlin.jvm'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

kotlin {
    jvmToolchain(Integer.parseInt(java_version))
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files(project(':common').sourceSets.main.output)
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
}

tasks.named('compileKotlin') {
    dependsOn(':common:classes')
}

tasks.named('test') {
    dependsOn(':common:classes')
}

test {
    useJUnitPlatform()
}
